/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f7f9fb",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-highest": "#e0e3e5",
        "on-surface-variant": "#534434",
        "tertiary-fixed-dim": "#7fd0ff",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#004c6a",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface": "#191c1e",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        primary: "#855300",
        "surface-tint": "#855300",
        "primary-fixed-dim": "#ffb95f",
        "tertiary-container": "#1abdff",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#f59e0b",
        "primary-fixed": "#ffddb8",
        error: "#ba1a1a",
        "inverse-primary": "#ffb95f",
        secondary: "#505f76",
        "outline-variant": "#d8c3ad",
        "on-primary-fixed-variant": "#653e00",
        "on-tertiary-container": "#004966",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#2a1700",
        "on-primary-container": "#613b00",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-container": "#54647a",
        "secondary-container": "#d0e1fb",
        outline: "#867461",
        "error-container": "#ffdad6",
        surface: "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        tertiary: "#00658b",
        "tertiary-fixed": "#c5e7ff",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-fixed": "#001e2d",
        "surface-container-low": "#f2f4f6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        grid_gutter: "16px",
        header_height: "64px",
        stack_md: "16px",
        sidebar_width: "240px",
        container_padding: "24px",
        stack_sm: "8px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk"],
        "mono-data": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        display: ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "table-data": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "1", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        display: ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "table-data": ["13px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
